"""updates

Revision ID: eac61359ad88
Revises: cdd7a444a408
Create Date: 2023-06-10 15:35:46.809855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac61359ad88'
down_revision = 'cdd7a444a408'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
